services:
  teslafullscreen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teslafullscreen_app
    ports:
      - "8097:8097"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
